// Generated by https://quicktype.io

export default interface ResultType {
    id:                   string;
    iri:                  string;
    short_form:           string;
    obo_id?:              string;
    label:                string;
    description?:         string[];
    ontology_name:        string;
    ontology_prefix:      string;
    type:                 string;
    is_defining_ontology: boolean;
}