// Generated by https://quicktype.io

export default interface ResultsTypes {
    responseHeader: ResponseHeader;
    response:       Response;
    facet_counts:   FacetCounts;
    highlighting:   Highlighting;
}

export interface FacetCounts {
    facet_queries:   Facet;
    facet_fields:    FacetFields;
    facet_dates:     Facet;
    facet_ranges:    Facet;
    facet_intervals: Facet;
    facet_heatmaps:  Facet;
}

export interface Facet {
}

export interface FacetFields {
    ontology_name:        Array<number | string>;
    ontology_prefix:      Array<number | string>;
    type:                 Array<number | string>;
    subset:               Array<number | string>;
    is_defining_ontology: Array<number | string>;
    is_obsolete:          Array<number | string>;
}

export interface Highlighting {
    "ncit:class:http://purl.obolibrary.org/obo/NCIT_C14238": NcitClassHTTPPurlObolibraryOrgOboNCITC14238;
}

export interface NcitClassHTTPPurlObolibraryOrgOboNCITC14238 {
    label:   string[];
    synonym: string[];
}

export interface Response {
    numFound: number;
    start:    number;
    docs:     Doc[];
}

export interface Doc {
    id:                   string;
    iri:                  string;
    short_form:           string;
    obo_id:               string;
    label:                string;
    description:          string[];
    ontology_name:        string;
    ontology_prefix:      string;
    type:                 string;
    is_defining_ontology: boolean;
}

export interface ResponseHeader {
    status: number;
    QTime:  number;
    params: Params;
}

export interface Params {
    "facet.field":    string[];
    hl:               string;
    fl:               string;
    start:            string;
    fq:               string;
    rows:             string;
    "hl.simple.pre":  string;
    bq:               string;
    q:                string;
    defType:          string;
    "hl.simple.post": string;
    qf:               string;
    "hl.fl":          string[];
    facet:            string;
    wt:               string;
}
